spring.application.name=hotelManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/hotelManagement
spring.datasource.username=postgres
spring.datasource.password=test@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# following code is used to defer the initialization of data source
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=never
#spring.sql.init.data-locations=classpath:data.sql
# whichever file we create in resources folder is directly accessible in classpath