spring.application.name=hotelManagementSystem

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

# following code is used to defer the initialization of data source
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=never
#spring.sql.init.data-locations=classpath:data.sql
# whichever file we create in resources folder is directly accessible in classpath

logging.level.org.springframework.security=DEBUG

jwt.secretKey=${JWT_SECRET_KEY}
jwt.tokenExpirationTime=3600
#in seconds

frontend.url=${FRONT_END_URL}

razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_EMAIL_ID}